require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'spec/factories/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'
